---
resources:
  - name: super-app
    type: git
    branch: ci
    source:
      uri: https://github.com/vannenc/concourse-tutorial.git

jobs:
  - name: Testing
    plan:
    - get: super-app
      trigger: true
    - aggregate:
      - task: lint
        file: super-app/ci/tasks/lint.yml
      - task: unit
        file: super-app/ci/tasks/unit.yml

  - name: Building & integeration testing
    plan:
    - get: super-app
      passed: ["Testing"]
      trigger: true

    - task: build
      file: super-app/ci/tasks/build.yml

    - task: integeration test
      file: super-app/ci/tasks/integeration.yml

