---
resources:
  - name: super-app
    type: git
    branch: ci
    source:
      uri: https://github.com/vannenc/concourse-tutorial.git

jobs:
  - name: Testing
    plan:
    - get: super-app
      trigger: true
    - aggregate:
      - task: lint
        file: super-app/ci/tasks/lint.yml
      - task: unit
        file: super-app/ci/tasks/unit.yml

  - name: Building & integeration testing
    plan:
    - get: super-app
      passed: ["Testing"]
      trigger: true


    - task: build
      file: super-app/ci/tasks/build.yml

    - task: integeration test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ./artifact/super_*_linux_amd64&
            ./super-app/scripts/test_integeration.sh  http://127.0.0.1:8080
            kill -9 `pgrep super_`
        inputs:
          - name: super-app
          - name: artifact