---
resources:
  - name: super-app
    type: git
    branch: ci
    source:
      uri: https://github.com/vannenc/concourse-tutorial.git

jobs:
  - name: Test
    plan:
    - get: super-app
      trigger: true
    - task: Testing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: ls
          args: ["-l", "super-app"]

        inputs:
          - name: super-app