---
resources:
  - name: super-app
    type: git
    branch: ci
    source:
      uri: https://github.com/vannenc/concourse-tutorial.git

jobs:
  - name: Testingg
    plan:
    - get: super-app
      trigger: true
    - aggregate:
      - task: lint
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang}
          run:
            path: ./test_fmt.sh
            dir: super-app/scripts
          inputs:
            - name: super-app

      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang}
          run:
            path: sh
            args:
            - -exc
            - |
              ./scripts/go_deps.sh
              ./scripts/test_unit.sh
            dir: super-app/
          inputs:
            - name: super-app

  - name: Building & integeration testing
    plan:
    - get: super-app
      passed: ["Testing"]
      trigger: true


    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ./scripts/go_deps.sh
            ./scripts/go_build.sh linux 0.0.1
            mv super_*_linux_amd64 ../artifact
          dir: super-app/
        inputs:
          - name: super-app
        outputs:
          - name: artifact

    - task: integeration test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ./artifact/super_*_linux_amd64&
            ./super-app/scripts/test_integeration.sh  http://127.0.0.1:8080
            kill -9 `pgrep super_`
        inputs:
          - name: super-app
          - name: artifact